"""Mensaje de la nueva migración

Revision ID: f544acaa6871
Revises: ec9419172a53
Create Date: 2024-08-04 14:46:34.841831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f544acaa6871'
down_revision = 'ec9419172a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.create_unique_constraint(None, ['nickname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('nickname',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
